# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='time_for_job',
            field=models.CharField(default=15, max_length=100),
            preserve_default=False,
        ),
    ]
