# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_userdetails_time_for_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('job_title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_address', models.CharField(max_length=500)),
                ('techinican', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techinican', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
