# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_technicianschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianschedule',
            name='techinican',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techinican', to='accounts.UserDetails'),
        ),
    ]
