# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190331_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='token_pickle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
