# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userdetails_token_pickle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='token_pickle',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
