# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190401_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='auth_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
