# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userdetails_auth_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_email_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
