# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userdetails_is_email_authenticated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianAppointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=1000)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_appointments', to='accounts.UserDetails')),
            ],
        ),
        migrations.RemoveField(
            model_name='technicianschedule',
            name='techinican',
        ),
        migrations.DeleteModel(
            name='TechnicianSchedule',
        ),
    ]
